name: subsocial_flutter_auth
description: A new Flutter package project.
version: 0.0.1
homepage: null

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  encrypt: ^5.0.1
  fast_immutable_collections: ^7.0.3
  flutter:
    sdk: flutter
  freezed_annotation: ^0.14.3
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.8
  sembast: ^3.1.1
  collection: ^1.15.0
  path_provider: ^2.0.5
  path: ^1.8.0
  state_notifier: ^0.7.1
  pointycastle: ^3.3.4
  subsocial_sdk:
    path: packages/subsocial_sdk

dev_dependencies:
  build_runner: ^2.1.4
  json_serializable:
  flutter_test:
    sdk: flutter
  freezed: ^0.14.5
  hive_generator: ^1.1.1
  lint: ^1.7.2
  mocktail: ^0.1.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter: null
# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.
# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
